version: "3"
services:
  TestUmbraco:
    restart: unless-stopped
    build: .
    tty: true
    network_mode: bridge
    ports:
      - "801:80"
    volumes:
      - media:/app/wwwroot/media
volumes:
  media:
    driver: local
    driver_opts:
      type: none
      device: /home/TestUmbracoData/media
      o: bind